# Image that includes Python and common data science packages
image: gitpod/workspace-python-3.10

# List of tasks to run on workspace start
tasks:
  - name: Setup Python Environment
    command: |
      pip install -r requirements.txt
      clear
      echo "Python environment ready!"
      echo "Try running: python process_usage.py your_exported_usage.csv"

# VS Code extensions that are helpful for Python development
vscode:
  extensions:
    - ms-python.python